# -*- coding: utf-8 -*-
"""first_coding_session_ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11L3LB5EfykfwHrXU-W4ZTKPYx4Mkunvm
"""

# print("Hello world! this is pavitra.")
print("Hello world! this is python.")

# How to comment a line/lines. "ctrl+?" or put "#" symbol

#  How to create variables.

 a = 6 # int
 b = 3.6 # float
 c = "pavitra" # str
 d = True # bool
 _e = "gkb6276543"

 # we can not start a variable name with any number(0,1,2,3,4,5,6,7,8,9)
 # we can not start a variable name with any special character, except underscore(_)

 # 6dog = 4 wrong method

 # Note: If you put any value between quotes will consider as "string"

f = "False"


print(type(f)) # find data type

g = 6
h = 7
_h =g+h

# print(g+h)
print(_h+2)

i = 8
j = 3
_j = i-j
# print(i-j)
print(_j-10)

k = 6
l = -5
_l = l*k

# print(k*l)
print(_l)

m = 100
 n = 15
_n = round(m/n,3)

print(_n)
 # print(m/n)

o = 100
p = 15

print(o//p)

q = 22

print(q**2)

r = 4

print(r**5)

# Ques: prepare at least 2 bodmas question from H.W.

import math
equation  = 10*(5+4)/11

print(equation)

result= math.ceil(equation)

result2= math.floor(equation)
print(result)
print("floored result",result2)

"""# Next Session"""

# How to take input from the user.

x = 5
y = 9

z = x+y
print(z)

x = int(input())
y = int(input())
z = x+y
print(z)

# how to take f-string statement.

x = int(input("Enter your 1st number: "))
y = int (input("Enter your 2nd number: "))
_y = float(input("Enter your 3rd number: "))

z = round(x+y+_y,2)
print(f"The sum of{x},{y}, and {_y} is {z}")
print(f"The sum of x, y, and _y is {z}")

n = str(input("Enter your full name: "))
o = str(input("Enter your organization name: "))


print(f"Hello, {n}")
print(f"Welcome to the{o}.")

# how to give conditional statement using if-elif-else.


num = int(input("Enter a number: "))

if num > 0:
  print("The number is positive.")
else:
  print("The number is negative.")

num = int(input("Enter a number: "))

if num > 0:
  print("The number is positive.")
elif num < 0:
  print("The number is negative.")
else:
  print("the number is zero.")

# practice Question.
# take input from user.
# print "Even" if the num is even.
# print "Odd" if the num is odd.
# print "Neutral" if the num is  zero.



user_input = int(input("Enter a number: "))

if  user_input%2==0 and user_input>0:
   print("Even")
elif user_input%2!=0:
  print("odd")
else:
  print("Neutral")

# practice question
# take input from user.
# if the num is even then get the square of it.
# if the num is  odd then multiply it with 10.
# if the num is zero then add 500 in it.



user_input = int(input("Enter a number: "))

if  user_input%2==0 and user_input>0:
  print("Number is even")
  print(f"The square of {user_input} is {user_input**2}")
elif user_input%2!=0:
  print("Number is odd")
  print(f"The multiplication of {user_input} is {user_input*10}")
elif user_input==0:
  print("Number is zero")
  print(f"The addition of {user_input} is {user_input+500}")

